name: bachelor test CI

on: [push]

jobs:
  ##############################################################################
  # JOB: LINT BACKEND ##########################################################
  ##############################################################################
  lint_backend:
    name: Lint backend
    runs-on: ubuntu-latest
    #needs: [nothing]
    steps:
      ##########################################################################
      # CHECKOUT CODE ##########################################################
      ##########################################################################
      - name: Checkout code
        uses: actions/checkout@v2
      ##########################################################################
      # LINT BACKEND ###########################################################
      ##########################################################################
      - name: backend | Lint
        run: |
          cd Server
          npm install
          npm run lint

  ##############################################################################
  # JOB: LINT FRONTEND #########################################################
  ##############################################################################
  lint_frontend:
    name: Lint frontend
    runs-on: ubuntu-latest
    #needs: [nothing]
    steps:
      ##########################################################################
      # CHECKOUT CODE ##########################################################
      ##########################################################################
      - name: Checkout code
        uses: actions/checkout@v2
      ##########################################################################
      # LINT FRONTEND ##########################################################
      ##########################################################################
      - name: frontend | Lint
        run: |
          cd Client
          npm install
          npm run lint
